export const HOME_TURN_ON_LOADING = 'HOME_TURN_ON_LOADING';
export const HOME_TURN_OFF_LOADING = 'HOME_TURN_OFF_LOADING';
export const HOME_TURN_OFF_ERROR = 'HOME_TURN_OFF_ERROR';
export const HOME_TURN_ON_ERROR = 'HOME_TURN_ON_ERROR';
export const HOME_REDIRECT = 'HOME_REDIRECT';
export const HOME_RESET_REDIRECT = 'HOME_RESET_REDIRECT';
